import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaJava,
  FaReact,
  FaNodeJs,
  FaPython,
  FaBootstrap,
  FaDatabase,
  FaGitAlt,
  FaGithub,
  FaUnlock,
//   FaRegistered,
//   FaBook,
} from "react-icons/fa";

import {
  SiTailwindcss,
  SiExpress,
  SiTypescript,
  SiMongodb,
  SiMysql,
  SiRedux,
  SiNextdotjs,
  SiFirebase,
  SiJquery,
  SiCplusplus,  
} from "react-icons/si";
import { FcManager } from "react-icons/fc";

export const MyappList = [
  { icons: <FaUnlock color="#e34c26" />, url: "login", appname: "User login"},
  { icons: <FcManager color="#e34c26" />, url: "register", appname: "User register" },
  { icons: <FaHtml5 color="#e34c26" />, url: "html", appname: "HTML" },
  { icons: <FaCss3Alt color="#264de4" />, url: "css", appname: "CSS" },
  { icons: <FaJs color="#f7df1e" />, url: "javascript", appname: "JavaScript" },
  { icons: <FaJava color="#007396" />, url: "java", appname: "Java" },
  { icons: <SiCplusplus color="#00599C" />, url: "cpp", appname: "C++" },
  { icons: <FaPython color="#306998" />, url: "python", appname: "Python" },
  { icons: <FaReact color="#61dafb" />, url: "react", appname: "React.js" },
  { icons: <FaNodeJs color="#68a063" />, url: "nodejs", appname: "Node.js" },
  { icons: <SiExpress />, url: "express", appname: "Express.js" },
  { icons: <FaBootstrap color="#7952b3" />, url: "bootstrap", appname: "Bootstrap" },
  { icons: <SiTailwindcss color="#38bdf8" />, url: "tailwind", appname: "Tailwind CSS" },
  { icons: <SiTypescript color="#007acc" />, url: "typescript", appname: "TypeScript" },
  { icons: <SiRedux color="#764abc" />, url: "redux", appname: "Redux" },
  { icons: <SiMongodb color="#4DB33D" />, url: "mongodb", appname: "MongoDB" },
  { icons: <SiMysql color="#00758f" />, url: "mysql", appname: "MySQL" },
  { icons: <FaDatabase />, url: "sql", appname: "SQL" },
  { icons: <SiNextdotjs />, url: "nextjs", appname: "Next.js" },
  { icons: <SiFirebase color="#FFCA28" />, url: "firebase", appname: "Firebase" },
  { icons: <SiJquery color="#0769ad" />, url: "jquery", appname: "JQuery" },
  { icons: <FaGitAlt color="#f1502f" />, url: "git", appname: "Git" },
  { icons: <FaGithub />, url: "github", appname: "GitHub" },
];
